# Generated by Django 4.0.4 on 2022-05-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczalnia',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('miasto', models.TextField()),
                ('ulica', models.TextField()),
                ('nr_lokalu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlytyCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zespol', models.CharField(max_length=255)),
                ('tytul', models.CharField(max_length=255)),
                ('gatunek', models.CharField(choices=[('Blues', 'Blues'), ('Country', 'Country'), ('Dance', 'Dance'), ('Electronica', 'Electronica'), ('Folk', 'Folk'), ('Funk', 'Funk'), ('Metal', 'Metal'), ('Hip hop', 'Hip hop'), ('Rap', 'Rap'), ('House', 'House'), ('Muzyka klasyczna', 'Muzyka klasyczna'), ('Inne', 'Inne'), ('Pop', 'Pop'), ('Jazz', 'Jazz')], default='Wybierz', max_length=40)),
                ('lista_utworów', models.TextField()),
                ('czas_trwania', models.CharField(max_length=255)),
                ('ID_wypozyczalni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.wypozyczalnia')),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('tytul', models.CharField(max_length=255)),
                ('gatunek', models.CharField(choices=[('Fantastyka', 'Fantastyka'), ('Sci–Fi', 'Science Fiction'), ('Romans', 'Romans'), ('Powieść historyczna', 'Powieść historyczna'), ('Horror', 'Horror'), ('Kryminał i thriller', 'Kryminał i thriller'), ('Biografia', 'Biografia'), ('Reportaż ', 'Reportaż'), ('Powieść młodzieżowa ', 'Powieść młodzieżowa'), ('Reportaż ', 'Reportaż'), ('Powieść naukowa', 'Powieść naukowa'), ('Poradnik', 'Poradnik'), ('Dla dzieci', 'Dla dzieci')], default='Wybierz', max_length=40)),
                ('ISBN', models.CharField(max_length=70)),
                ('ID_wypozyczalni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.wypozyczalnia')),
            ],
        ),
        migrations.CreateModel(
            name='Filmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezyser', models.CharField(max_length=255)),
                ('tytul', models.CharField(max_length=255)),
                ('gatunek', models.CharField(choices=[('Akcji', 'Akcji'), ('Animowany', 'Animowany'), ('Biograficzny', 'Biograficzny'), ('Dokumentalny', 'Dokumentalny'), ('Dramat', 'Dramat'), ('Edukacyjny', 'Edukacyjny'), ('Familijny', 'Familijny'), ('Fantasy', 'Fantasy'), ('Science-Fiction', 'Science-Fiction'), ('Horror', 'Horror'), ('Historyczny', 'Historyczny'), ('Komedia', 'Komedia'), ('Kryminał', 'Kryminał'), ('Obyczajowy', 'Obyczajowy'), ('Polityczny', 'Polityczny'), ('Przyrodniczy', 'Przyrodniczy'), ('Religijny', 'Religijny'), ('Romans', 'Romans'), ('Sport', 'Sport'), ('Thriller', 'Thriller')], default='Wybierz', max_length=40)),
                ('czas_trwania', models.CharField(max_length=255)),
                ('ID_wypozyczalni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.wypozyczalnia')),
            ],
        ),
    ]
