# Generated by Django 4.0.4 on 2022-05-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_rename_ksiazki_book_rename_plytycd_cd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='lista_utworów',
            new_name='lista_utworow',
        ),
    ]
