# Generated by Django 4.0.4 on 2022-05-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0004_rename_lista_utworów_cd_lista_utworow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='czas_trwania',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='movie',
            name='czas_trwania',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='rental',
            name='miasto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='nr_lokalu',
            field=models.CharField(max_length=25),
        ),
    ]
