# Generated by Django 4.0.4 on 2022-06-11 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0005_alter_cd_czas_trwania_alter_movie_czas_trwania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField()),
                ('deposit_length', models.DateField()),
                ('depositet_book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.book')),
                ('depositet_cd', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.cd')),
                ('depositet_movie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
