# Generated by Django 4.0.4 on 2022-06-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0006_alter_book_isbn_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dostepna',
            field=models.BooleanField(default=True),
        ),
    ]
